services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    # networks:
    #   - istsos4_shared_net

# networks:
#   istsos4_shared_net:
#     external: true