services:
  grafana-dev:
    build:
      context: .
      dockerfile: .config/Dockerfile.dev
      target: development
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.3}
        development: "true"
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    
    container_name: 'istsos4-grafana-dev-livereload'    
    user: root
    
    ports:
      - "3000:3000"    # Grafana web interface
      - "2345:2345"    # Delve debugger port
      - "35729:35729"  # LiveReload port
    
    volumes:
      # Mount the entire plugin source for live development
      - .:/plugin
      # Mount node_modules as a named volume
      - node_modules:/plugin/node_modules
      # Mount dist directly to Grafana plugins directory
      - ./dist:/var/lib/grafana/plugins/istsos4-istsos4grafana-datasource
      # Mount provisioning
      - ./provisioning:/etc/grafana/provisioning
    
    environment:
      NODE_ENV: development
      
      # Grafana Configuration
      GF_LOG_FILTERS: plugin.istsos4-istsos4grafana-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: istsos4-istsos4grafana-datasource
      GF_INSTALL_PLUGINS: orchestracities-map-panel
      
      # Security settings for development
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_DEFAULT_APP_MODE: "development"
      
      # Enable live reload
      ENABLE_LIVE_RELOAD: "true"
    
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    
    cap_add:
      - SYS_PTRACE

volumes:
  node_modules:
